---
# yamllint disable rule:line-length

name: tests
on:  # yamllint disable-line rule:truthy
  push:
    branches: ["main", "ocm-*", "release-*"]
    tags: ["*"]
  pull_request:
    branches: ["main", "ocm-*", "release-*"]
  schedule:
    - cron: "0 4 * * 1"  # 4:00 every Monday

env:
  GO_VERSION: "1.16"
  GO111MODULE: "on"
  GOPROXY: "https://proxy.golang.org"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install prereqs
        run: |
          echo 'APT::Acquire::Retries "5";' | sudo tee /etc/apt/apt.conf.d/80-retries
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y python3-pip ruby
          sudo gem install asciidoctor mdl
          sudo pip3 install yamllint

      - name: Run linters
        run: ./.ci-scripts/pre-commit.sh --require-all

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out source code
        uses: actions/checkout@v2
        with:
          path: main

      - name: Tidy
        run: cd main && go mod tidy && git diff --quiet HEAD

      - name: Build
        run: cd main && go build ./...

      - name: Test
        run: cd main && go test -v ./...

  # This is a dummy job that can be used to determine success of CI
  # This job should depend on all tests that must pass
  test-success:
    name: Successful tests
    needs: [build, lint]
    runs-on: ubuntu-20.04
    steps:
      - name: Success
        run: echo "Previous steps were successful"
